
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["304 305 1", "304 305 2", "304 305 3", "304 305 4", "304 305 5", "304 305 6", "304 305 7", "304 305 8", "304 305 9", "304 305 10", "304 305 11", "304 305 12", "304 305 13", "304 305 14", "304 305 15", "304 305 16", "304 305 17", "304 305 18", "304 305 19", "304 305 20", "304 305 21"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
